/***********************************************
 *                                              *
 *     Combined Reducers for main application   *
 *     Generated by ts2redux                    *
 *                                              *
 ***********************************************/
import * as redux from "redux";
import { IIncModel, IncModelReducer } from "./IncModel";
export interface IState {
  IncModel: IIncModel;
}
// use reducerObject if you combine reducers manually
// for example when using connected-react-router
export const reducerObject = {
  IncModel: IncModelReducer
};
export const reducers = redux.combineReducers<IState>(reducerObject);
